---
title: "joint Land Use"
output: html_notebook
---

```{r, message = FALSE}
library(sf)
library(raster)
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(readxl)
library(stringr)
```

### read in LandUse type from different source Raster
```{r}
LandUse_NMD <- readRDS(here("data", "LandUse_NMD_points_500m.Rds"))
LandUse_SJB <- readRDS(here("data", "LandUse_SJB_points_500m.Rds"))
LandUse_TUVA <- readRDS(here("data", "LandUse_TUVA_points_500m.Rds"))
```

### read in metadata

```{r}
# metadata
NMD <- raster(here("data", "NMD", "nmd2018bas_ogeneraliserad_v1_0.tif")) 
NMD_pasture <- raster(here("data", "NMD_Tillaggsskikt_Markanvandning", "NMD_markanv_bete_v1.tif"))


# NMD_build_areas <- raster(here("data", "NMD_Tillaggsskikt_Markanvandning", "NMD_markanv_anlagda_omr_v1.tif"))
# NMD_kraft <- raster(here("data", "NMD_Tillaggsskikt_Markanvandning", "NMD_markanv_kraftledning_v1.tif"))

NMD_meta <- 
NMD@data@attributes %>% 
  as.data.frame() %>% 
  dplyr::select(-Opacity, -COUNT) %>% 
  filter(Klass != "") %>% 
  mutate(Klass = iconv(as.character(Klass), "latin1")) %>% 
  rename(NMD_base = ID)

NMD_pasture_meta <- 
  NMD_pasture@data@attributes %>% 
  as.data.frame() %>% 
  dplyr::select(-Opacity) %>% 
  filter(Klass != "") %>% 
  mutate(Klass = iconv(as.character(Klass), "latin1"))

# NMD_build_areas_meta <- 
#   NMD_build_areas@data@attributes %>% 
#   as.data.frame() %>% 
#   dplyr::select(-Opacity) %>% 
#   filter(Klass != "") %>% 
#   mutate(Klass = iconv(as.character(Klass), "latin1")) %>% 
#   rename(Buildings = ID)

# NMD_kraft_meta <- 
#   NMD_kraft@data@attributes %>% 
#   as.data.frame() %>% 
#   dplyr::select(-Opacity) %>% 
#   filter(Klass != "") %>% 
#   mutate(Klass = iconv(as.character(Klass), "latin1"))

```


### regroup cropdata to groups

```{r}
SJB_meta <- 
  read_xlsx(here("data", "crop_codes_english.xlsx")) %>% 
  rename(Landuse_code = `Landuse code`) %>% 
  dplyr::select(Landuse_code, English) %>% 
  distinct() %>% 
  group_by(Landuse_code) %>% 
  filter(row_number()==n()) #this selects the most recent definition of the crop_code if they have been redifined over the years. However, the meaning of the crop code doesn't change substantially in most cases and in no major case
 
LandUse_SJB_filt <- 
LandUse_SJB %>% 
  filter(apply(dplyr::select(., starts_with("SJB")), 1, function(x) all(!is.na(x))))

# n_max maximum prct of LandUse in any Buffer in any route in any year
# n_mean average prct of LandUse among Buffer were LandUse occures
# occurence_prct proportion of Buffer with LandUse


LandUse_SJB_max <- 
LandUse_SJB_filt %>% 
  dplyr::select(karta, position, starts_with("SJB")) %>% 
  gather(year, Landuse_code, -karta, -position) %>% 
  group_by(year, karta, position, Landuse_code) %>% 
  summarize(n = n()) %>%
  mutate(n = round(100*n/7853, 2)) %>% 
  group_by(Landuse_code) %>% 
  summarize(max_use_prct = max(n),
            mean_use_prct = round(mean(n),2),
            occurence_prct = round(100*(n()/46336),2)) %>% #724 routes * 8 points * 8 years
  arrange(desc(max_use_prct)) %>% 
  left_join(SJB_meta) 

LandUse_SJB_max %>% 
  mutate(English = str_trunc(English, 25, "right"))

# export LandUse codes for regrouping
# write_csv2(LandUse_SJB_max, here("data", "CropCodes.csv"))

```

#### recode

```{r}

LandUse_SJB_groups <- 
  read_csv2(here("data", "CropCodes.csv"))

LandUse_SJB_groups <-
  LandUse_SJB_groups %>% 
  mutate(crop_groups = case_when(
    Landuse_code %in% c(52,54,55,56,89,95,96) ~ "Pasture",
    Landuse_code %in% c(49,50,51,53,57,58,59,80,81) ~ "Ley",
    Landuse_code %in% c(1,3,4,7,8,12,20,22) ~ "Winter_cereal",
    Landuse_code %in% c(2,5,9,21,23,30,31) ~ "Spring_cereal",
    Landuse_code %in% c(60,62,69) ~ "Fallow",
    Landuse_code %in% c(46,47,32,35) ~ "Tuber_Root",
    Landuse_code %in% c(65,67,68) ~ "Woody_crops",
    TRUE ~ "Other"))

LandUse_SJB_groups %>% 
  mutate(English = str_trunc(English, 25, "right")) %>% 
  arrange(crop_groups)

LandUse_SJB_rec <- 
  LandUse_SJB %>% 
  mutate_at(vars(starts_with("SJB_")), function(x) {
    LandUse_SJB_groups[ match( x, LandUse_SJB_groups$Landuse_code),]$crop_groups
  })

Crop_rotations <- 
LandUse_SJB_rec %>% 
  filter_at( vars(starts_with("SJB_")), function(x) !is.na(x)) %>% 
  select(starts_with("SJB")) 
  group_by_all() %>% 
  summarize(n = n()) %>% 
  ungroup %>% 
  mutate(n_prct = round(n/sum(n), 4)*100) %>% 
  arrange(desc(n)) %>% 
  mutate_at(vars(starts_with("SJB")), function(x) (str_trunc(x, 15, "right")))

Crop_rotations
```

```{r}
Crop_rotations %>% 
  mutate(combo = 1:n()) %>% 
  gather(year, crop, -n, -n_prct, -combo) %>% 
  group_by(combo) %>% 
  summarize(div = exp(diversity(table(as.numeric(as.factor(crop))))),
            N_comb = length(unique(crop)),
            n = unique(n)) %>%  
  group_by(div) %>% 
  summarize(N_comb = unique(N_comb),
            n_combo = n(),
            n = sum(n)) %>% 
  arrange(desc(n)) %>% 
  mutate(n_prct = round(n/sum(n), 4)*100)
```


## summarize Landuse classes

### NMD bassikt

```{r}

LandUse_max <- 
LandUse_NMD %>% 
  dplyr::select(karta, position, NMD_base) %>% 
  group_by(karta, position, NMD_base) %>% 
  summarize(n = n()) %>%
  mutate(n = round(100*n/7853, 2)) %>% 
  group_by(NMD_base) %>% 
  summarize(max_use_prct = max(n),
            mean_use_prct = round(mean(n),2),
            occurence_prct = round(100*(n()/5792),2)) %>%  #724 routes * 8 points
  arrange(desc(occurence_prct)) %>%
  left_join(NMD_meta) %>% 
  select(1,5,2:4) %>% 
  mutate(Klass = str_trunc(Klass, 25, "right"))

LandUse_max %>% 
  arrange(NMD_base)

```

### NMD_buildings

```{r}

LandUse_Buildings_max <- 
LandUse_NMD %>% 
  dplyr::select(karta, position, Buildings) %>% 
  na.omit() %>% 
  group_by(karta, position, Buildings) %>% 
  summarize(n = n()) %>%
  mutate(n = round(100*n/7853, 2)) %>% 
  group_by(Buildings) %>% 
  summarize(max_use_prct = max(n),
            mean_use_prct = round(mean(n),2),
            occurence_prct = round(100*(n()/5792),2)) %>%  #724 routes * 8 points
  arrange(desc(occurence_prct)) %>%
  left_join(NMD_build_areas_meta) %>% 
  mutate(Klass = str_trunc(Klass, 25, "right")) %>% 
  select(1,6,2:5)

LandUse_Buildings_max 
```

## LandUse combos

### full combinations

```{r}
LandUse_combos <- 
LandUse_NMD %>% 
  cbind(., select(LandUse_SJB_rec, starts_with("SJB_"))) %>% 
  #filter(NMD_base == 3) %>% 
  select(-c(1:5)) %>% 
  gather(year, Landuse, -NMD_base, -Pasture, -Buildings, -Powerlines) %>% 
  select(-year) %>% 
  group_by_all() %>% 
  summarize(n = n()) %>% 
  ungroup %>% 
  left_join(NMD_build_areas_meta) %>% 
  mutate(Klass = str_trunc(Klass, 25, "right")) %>% 
  mutate(Buildings = Klass) %>% 
  select(-Klass, -COUNT) %>% 
  left_join(NMD_meta) %>% 
  mutate(Klass = str_trunc(Klass, 25, "right")) %>% 
  mutate(NMD_base = Klass) %>% 
  select(-Klass) %>% 
  arrange(desc(n)) %>% 
  mutate(n_prct = 100*round(n/sum(n),4))

LandUse_combos_all <-   
LandUse_combos %>% 
  filter(! is.na(Pasture & is.na(Buildings) & is.na(Powerlines & is.na(Landuse)))) %>% 
  mutate(n_prct = 100*round(n/sum(n),4)) %>% 
  group_by(NMD_base) %>% 
  mutate(n_group = sum(n)) %>% 
  ungroup() %>% 
  arrange(desc(n_group), desc(n))

LandUse_combos_all

```

### combinatinos with SJB

```{r}
LandUse_combos_SJB <- 
LandUse_combos_all %>% 
  select(-Pasture, -Buildings, -Powerlines) %>% 
  filter(!is.na(Landuse)) %>% 
  group_by(NMD_base, Landuse) %>% 
  summarize(n = sum(n)) %>%
  ungroup() %>% 
  mutate(n_prct = round(n/sum(n),4)*100) %>% 
  arrange(desc(n))

LandUse_combos_SJB
```

### combinations with Buildings Layer

```{r}

LandUse_combos_Build <- 
LandUse_combos_all %>% 
  select(-Pasture, -Landuse, -Powerlines) %>% 
  filter(!is.na(Buildings)) %>% 
  group_by(NMD_base, Buildings) %>% 
  summarize(n = sum(n)) %>%
  ungroup() %>% 
  mutate(n_prct = round(n/sum(n),4)*100) %>% 
  arrange(desc(n))

LandUse_combos_Build
```

