---
title: "Swedish Bird habitat model"
subtitle: "Project Notes"
author: "Fabian Roger"
output: html_notebook
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# 2019-02-25

2 main methods for surveying Birds:

**freely chosen route with point surveying**

[summer routes](http://www.fageltaxering.lu.se/inventera/metoder/punktrutter/metodik-sommarpunktrutter)

[vinter routes](http://www.fageltaxering.lu.se/inventera/metoder/punktrutter/metodik-vinterpunktrutter)

+ since 1975
+ observer chooses route freely
+ 20 stop points along route on which birds are recorded for 5 min
+ min 300 m between points (in forest) or 400 m (in open terrain)
+ _all birds_ are counted from _each point_

+ once in the summer, once or 5 times in winter, approximately same dates and starting times

**fixed standard routes**

[description](http://www.fageltaxering.lu.se/inventera/metoder/standardrutter/metodik-standardrutter)

+ since 1996
+ 8 km long (square of 2x2)
+ starting heading north, then east
+ routes are fixed and have a minimum distance of 25 km to all sites
+ 716 routes in total, spread systematically over the whole of Sweden
+ coordinates given in RT90 2.5 gon V0:-15 _not_ SWEREF99


Pointcounts:

+ on each corner and halfway between each corner a point count takes place (5 min)
+ all seen or heard birds are recorded _independent_ from birds on lines
+ point count should be performed on the point itself or else from the nearest reachable point within 200 m from the point itsel
+ double counting should be avoided across points - if a sighting represents the same bird detected from more than one point is up to the observer to judge

Linecounts:

+ along the route, birds are recorded during slow walk, min 30 min per full km, approx 30-40 min / km
+ the lines should be followed as close as possible
+ obstacles should be circumvented (e.g. lakes or fields), the counting continious as long as the observer is within 200m of the line. If the observer has to leave the 200 m corridor, recording should be interupted until the corridor is reached again.
+ small obstacles should be overcome were possible and the counting should be taken up again on the other side. 
+ doublecounting should be avoided, also across line transects
+ binoculars are discouraged

+ nestlings should not be counted
+ counting should start at 4 a.m. sommer time, (±30 min) but not earlier than 30 min before sunrise
+ the start time of each point count and the effctive inventory time of each line transect should be recorded
+ teh date should be during the high breeding season for most species after the arrival and establishment of migratory species. Exact dates vary with latitude but start from may 15th in the south to June 15th in the north / the mountain regions. 
+ the same routes should be visited within ±5 days compared to last year

# 2019-02-26

Lindbladh et al 2017: Avian diversity in Norway spruce production forests


+ looked at bird diveristy in spruce ( _Picea abies_) monoculture in souther Sweden
+ stands are even-aged, have a rotation period between 45 and 70 years and are thinned 2-3 times before
+ young stands are dominated by broadleaves, mainly birch, naturally regenerated
+ used point counts, with 40 / 50 m radius

+ found strong differences in species composition between < 15 years and older forest
    + old forest = common forest birds
    + < 15 years =  habitat also for farmland species but also including migrants
+ inclusinion of < 15 % of broadleave tree species has positive effect on bird richness in old stands


Thoughts: 
 + can we model bird functional diversity in relation to habitat type (eitehr directly or as emrging property from the full community)
 + data are on route level, but what scale are we interested in? 
 + if we replace open landscape by forestry, how much FB diversity will be lost, how much maintained on clear cuts? How much does this depend on remaining farmland nearby?


# 2019-03-01

Discussion with Niklas:

+ we have Landuse data only for one timepoint
+ we have clearcut data going back in time but only know when it was cut, not when it was replanted
+ we could probably make a historic classification with LandSat data but we need to discuss what we want exactly

Thoughts:

+ should we model routes or should we aggregate larger landscapes and then average out both routes and landscape features? Teh latter is maybe also more compatible with the output of Agripolis

+ if we do a stacked SDM, can we include landscape features of different radii for different birds (if modeled at route level)







