---
title: "Worldclim characterization"
output: html_notebook
---

```{r, message = FALSE}
library(sf)
library(raster)
library(dplyr)
library(tidyr)
library(here)
library(future.apply)
library(readxl)
library(corrplot)
library(ggplot2)
```

## load bird routes

```{r}
Standard_geo <- read_sf(here("data", "Standard_routes_geo.gpkg"))
Standard_geo <- st_transform(Standard_geo, "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0 ")
#Freecounts_geo <- read_sf(here("data", "Standard_routes_geo.gpkg"))

#subset for jkp (for plotting)
JKP_karta <- readRDS(here("data", "JKP_karta.RDS"))
```


## load wordclim data


```{r}
worldclim <- brick(here("data", "WordClimSweden05.tif"))
```

from worldclim website:

~~~
BIO1 = Annual Mean Temperature
BIO2 = Mean Diurnal Range (Mean of monthly (max temp - min temp))
BIO3 = Isothermality (BIO2/BIO7) (* 100)
BIO4 = Temperature Seasonality (standard deviation *100)
  BIO5 = Max Temperature of Warmest Month
BIO6 = Min Temperature of Coldest Month
BIO7 = Temperature Annual Range (BIO5-BIO6)
BIO8 = Mean Temperature of Wettest Quarter
BIO9 = Mean Temperature of Driest Quarter
BIO10 = Mean Temperature of Warmest Quarter
BIO11 = Mean Temperature of Coldest Quarter
  BIO12 = Annual Precipitation
BIO13 = Precipitation of Wettest Month
BIO14 = Precipitation of Driest Month
BIO15 = Precipitation Seasonality (Coefficient of Variation)
BIO16 = Precipitation of Wettest Quarter
BIO17 = Precipitation of Driest Quarter
BIO18 = Precipitation of Warmest Quarter
BIO19 = Precipitation of Coldest Quarter

Please note that the temperature data are in °C * 10. This means that a value of 231 represents 23.1 °C. This does lead to some confusion, but it allows for much reduced file sizes which is important as for many downloading large files remains difficult. The unit used for the precipitation data is mm (millimeter).
~~~



**make buffer for raster extraction** 
```{r}

# make a 1km buffer around each route
Standard_geo_buffer <- 
  Standard_geo %>% 
  st_transform(crs = "+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs ") %>% 
  group_by(karta) %>% 
  summarise() %>% 
  st_convex_hull() %>% 
  st_buffer(1000) 

jkp <- 
  filter(Standard_geo_buffer, karta %in% JKP_karta) %>% 
    summarise() %>% 
    st_convex_hull() %>% 
    crop(worldclim, .)

jpk_points <- 
  filter(Standard_geo_buffer, karta %in% JKP_karta) %>% 
  group_by(karta) %>% 
  st_centroid() %>% 
  st_coordinates() %>% 
  SpatialPoints(coords = ., proj4string = CRS("+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs "))



{
  jpeg(filename = here("plots", "Worldclim_jkp.jpg"), width = 900, height = 480)
  par(mfrow = c(1,2))
  plot(jkp[[5]], main = "BIO 5")
  plot(jpk_points, add = T, cex = 0.5, col = "black")
  plot(jkp[[12]], main = "BIO 12")
  plot(jpk_points, add = T, cex = 0.5, col = "black")
  dev.off()
  }


{
  par(mfrow = c(1,2))
  plot(jkp[[5]], main = "BIO 5")
  plot(jpk_points, add = T, cex = 0.5, col = "black")
  plot(jkp[[12]], main = "BIO 12")
  plot(jpk_points, add = T, cex = 0.5, col = "black")
}

```



```{r}
plan(multiprocess, workers = 4)

# extract climate data for each route
Buffer_list <- 
  Standard_geo_buffer %>% 
  split(.$karta) 

worldclim_Raster_list <- future_lapply(Buffer_list, function(x) try(crop(worldclim, x)))

plan(sequential)


```



```{r}
# vector of route names 
Routes <- names(worldclim_Raster_list)

plan(multiprocess, workers = 4)

wordclim_karta_list <- 
  
  future_lapply(Routes, function(x) {
  
  filter(Standard_geo_buffer, karta == x) %>% 
      raster::extract(x = worldclim_Raster_list[[x]],
                      df = T) %>%
      as_tibble%>%
      mutate(karta = x)
  
  })


route_clim <- bind_rows(wordclim_karta_list)

route_clim <- 
  route_clim %>% 
  dplyr::select(-ID) %>% 
  dplyr::select(karta, starts_with("WordClimSweden")) %>% 
  rename_at(vars(starts_with("WordClimSweden")), function(x) gsub("WordClimSweden05\\.(\\d+)","WCS_\\1", x)) %>% 
  group_by(karta) %>% 
  summarise_at(vars(starts_with("WCS")), function(x) mean(x, na.rm = T))


write_tsv(route_clim, here::here("data", "WorldClimRoutes.csv"))

route_clim <- read_tsv(here("data", "WorldClimRoutes.csv"))

dplyr::select(route_clim, -karta) %>%
  dplyr::select("WCS_1", "WCS_4", "WCS_13") %>% 
  #mutate_all(scale) %>%  
  cor(use = "pairwise.complete.obs") %>%
  corrplot(method = "ellipse", diag = F, type = "lower", tl.col = "black", tl.cex = 0.6, tl.srt = 60)
```


```{r}
route_clim %>% 
  dplyr::select(-karta) %>%
  summarize_all(list("min" = function(x) min(x, na.rm = T),
                     "max" = function(x) max(x, na.rm = T))) %>% 
  gather(var, val) %>% 
  mutate(stat = gsub(".+_(\\w+$)", "\\1", var),
         var = gsub("(.+)_\\w+$", "\\1", var)) %>% 
  spread(stat, val)

clim_pca_data <- 
route_clim %>% 
  gather(var, val,-karta) %>% 
 # mutate(val = val + abs(min(val, na.rm = T))) %>% 
  group_by(var) %>% 
 #mutate(val = val / max(val, na.rm = T))
  mutate(val = scale(val))

ggplot(clim_pca_data, aes(x = var, y = val))+
  geom_violin()+
  coord_flip()+
  geom_hline(aes(yintercept = 0))
  
clim_pca <- 
  clim_pca_data %>%
  spread(var, val) %>% 
  na.omit() %>% 
  dplyr::select(-karta) %>% 
  princomp()

biplot(clim_pca,  var.axes = TRUE, cex = c(0.2,0.6))
```


```{r}
clim_clust <- 
clim_pca_data %>%
  spread(var, val) %>% 
  as.data.frame()

varcomb_3 <- t(combn(unique(clim_pca_data$var), 3, simplify = T))

climdist <- 
  apply(varcomb_3, 1, function(x){
  
  temp <- select(clim_clust, x) %>% 
    t() %>% 
    vegdist(method = "euc") %>% 
    sum()
  
  tibble(comb = paste(x, collapse = "_"),
         dist = temp)
}) %>% do.call("rbind", .)

climdist %>% filter(dist == max(dist))

rownames(clim_clust) <- clim_clust$karta  

clim_clust <- 
clim_clust %>% 
  select(-karta) %>% 
  t() %>% 
  vegdist(method = "euc") 

hclust(clim_clust) %>% plot

```


```{r}
tibble(comp = paste("Comp.", formatC(1:19, width = 2, flag = 0)),
       varexp = clim_pca$sdev/sum(clim_pca$sdev)) %>% 
  mutate(cumvar = cumsum(varexp)) %>% 
  ggplot(aes(x = comp, y = varexp))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = paste(round(varexp,2)*100, "%", sep = ""), y = varexp+0.05))+
  geom_text(aes(label = paste(round(cumvar,2)*100, "%", sep = ""), y = varexp+0.1), size = 3)+
  scale_y_continuous(limits = c(0,1))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("variance explained")
  
```

```{r}

clim_pca$loading[,1:4] %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "WC") %>% 
  gather(component, loading, -WC) %>% 
  # mutate(label = case_when(WC == "WCS_4" ~ "Temperature Seasonality (standard deviation *100)",
  #                          WC == "WCS_12" ~ "Annual Precipitation",
  #                          TRUE ~ NA_character_)) %>% 
  ggplot(aes(x = WC, y = loading))+
  facet_wrap(~component)+
  geom_bar(stat = "identity")+
  #geom_label(aes(label = label))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  ggtitle("loadings on first two components")
  

```

WC 11 = Mean Temperature of Coldest Quarter
WC 6  = Min Temperature of Coldest Month
WC 9  = Mean Temperature of Driest Quarter

